#!/usr/bin/env bash

set -eu

lein clean
DEBUG=1 LEIN_SNAPSHOTS_IN_RELEASE=true lein uberjar

# mkdir -p ../../Downloads/plugins/
cp target/uberjar/couchbase.metabase-driver.jar ../../Downloads/plugins/
