FROM metabase/metabase:latest
ADD https://github.com/xavierchow/metabase-couchbase-driver/releases/download/v1.0.0/couchbase.metabase-driver.jar /plugins/
RUN chmod 744 /plugins/couchbase.metabase-driver.jar


